In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.4.2


In [3]:
a=np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [9]:
b=np.array([[1,2,3],
            [3,4,3],
            [5,6,3]])

print(b)

[[1 2 3]
 [3 4 3]
 [5 6 3]]


In [14]:
print(np.zeros((3,3)))
print()
b=np.ones((2,2))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]]


In [16]:
c=np.empty((3,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
a=np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [24]:
a=np.linspace(0,10,5) #used for evenly spaced vals
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [47]:
a=np.ones((6,2,2))
print(a)
print(a.shape)


[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
(6, 2, 2)


In [48]:
print(a.ndim)

3


✅ Basic Idea
import numpy as np
🔹 1D Array (Vector)
arr = np.array([1, 2, 3, 4])
print(arr.ndim)

Output:

1

✔ Only one axis → just a list of values

🔹 2D Array (Matrix)
arr = np.array([[1, 2],
                [3, 4]])
print(arr.ndim)

Output:

2

✔ Two axes → rows and columns

🔹 3D Array
arr = np.array([[[1, 2],
                 [3, 4]]])
print(arr.ndim)

Output:

3

✔ Three axes → like stacked matrices

✅ What Does Dimension Actually Mean?
Array Type	Shape Example	ndim
Scalar	5	0
1D Array	(4,)	1
2D Array	(2,2)	2
3D Array	(1,2,2)	3
✅ Difference Between ndim and shape

ndim → tells how many axes

shape → tells size of each axis

Example:

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.ndim)   # 2
print(arr.shape)  # (2, 3)

✔ 2 dimensions
✔ 2 rows and 3 columns

In [51]:
a=np.zeros((2,3))
print(a)
print(a.size)#total elements

[[0. 0. 0.]
 [0. 0. 0.]]
6


In [53]:
print(a.dtype)
a.astype(int) #type casting

float64


array([[0, 0, 0],
       [0, 0, 0]])

In [61]:
arr = np.array([10, 20, 30, 40])
print(arr)
print(arr[0])
print(arr[-1])



[10 20 30 40]
10
40


In [76]:
print(arr)
print(arr[1:3])
print(arr[:2])
print(arr[::2])

[10 20 30 40]
[20 30]
[10 20]
[10 30]


In [82]:
mat=np.array([[1,2,3],[4,5,6]])
print(mat[0,0])
print(mat[:,1])

1
[2 5]


In [84]:
arr = np.array([10, 25, 30, 20])
print(arr[arr>=20])

[25 30 20]


In [90]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)
print(a**b)
print(a/b)

[5 7 9]
[ 4 10 18]
[  1  32 729]
[0.25 0.4  0.5 ]


In [91]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])


print(a+b)

[[2 4 6]
 [5 7 9]]


In [94]:
arr = np.array([1,2,3,4])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))#calc population variance and std
print(np.var(arr))


10
2.5
1
4
1.118033988749895
1.25


✅ How to Calculate Sample Variance?

Use the ddof parameter:

np.var(arr, ddof=1)
np.std(arr, ddof=1)

In [118]:
mat=np.array([[1,2,3],[4,5,6]])
print(np.sum(mat, axis=0))  # column-wise
print(np.sum(mat, axis=1))  # row-wise

[5 7 9]
[ 6 15]


In [99]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [100]:
a.reshape(2, 3)


array([[0, 1, 2],
       [3, 4, 5]])

In [104]:
mat.ravel()

array([1, 2, 3, 4, 5, 6])

📌 Difference Between flatten() and ravel() in NumPy
🔹 1️⃣ flatten()
arr.flatten()

Returns a copy

Changes to result do NOT affect original array

Slightly slower (because memory is duplicated)

Example:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
flat = arr.flatten()

flat[0] = 99

print(arr)
print(flat)

Output:

[[1 2]
 [3 4]]

[99  2  3  4]

✔ Original array unchanged.

🔹 2️⃣ ravel()
arr.ravel()

Returns a view (if possible)

Changes to result may affect original array

Faster (no new memory allocation)

Example:
arr = np.array([[1, 2], [3, 4]])
rav = arr.ravel()

rav[0] = 99

print(arr)
print(rav)

Output:

[[99  2]
 [ 3  4]]

[99  2  3  4]

✔ Original array changed.

In [111]:
a=a.reshape(2, 3)
a=a.reshape(2, 3)
print(a)
a.T

[[0 1 2]
 [3 4 5]]


In [113]:
mat = np.array([[1,2,3],
                [4,5,6]])
mat.T


array([[1, 4],
       [2, 5],
       [3, 6]])

In [119]:
print(mat)

[[1 2 3]
 [4 5 6]]


In [124]:
np.vstack((mat,mat))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [126]:
np.hstack((mat,mat))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [127]:
print(mat)

[[1 2 3]
 [4 5 6]]


In [132]:
a,b=np.split(mat,2)
print(a)
print(b)

[[1 2 3]]
[[4 5 6]]


In [139]:
a,b,c=np.split(mat,3,axis=1)
print(f"{a} \n\n,{b},\n\n {c}")

[[1]
 [4]] 

,[[2]
 [5]],

 [[3]
 [6]]


In [160]:
a=np.array([1,2,3,4,5,6])
a=a.reshape(2,3)
b=np.arange(7,13)
b=b.reshape(3,2)


In [163]:
print(a)
print(b)
a@b
np.dot(a,b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


array([[ 58,  64],
       [139, 154]])

In [191]:
c=np.array([7,8,9])
b=a[0:3]
print(b)

b[:,0]=3
print(b)

[[3 3 3]
 [4 5 6]
 [7 8 9]]
[[3 3 3]
 [3 5 6]
 [3 8 9]]


In [193]:
np.linalg.inv(b)


array([[ 0.33333333,  0.33333333, -0.33333333],
       [ 1.        , -2.        ,  1.        ],
       [-1.        ,  1.66666667, -0.66666667]])

In [195]:
np.linalg.det(b)


np.float64(-8.999999999999993)

In [194]:
np.linalg.eig(b)

EigResult(eigenvalues=array([15.61855057,  1.71704752, -0.33559808]), eigenvectors=array([[-0.31353728, -0.85417516,  0.1400107 ],
       [-0.53274104, -0.13646916, -0.77363824],
       [-0.7860543 ,  0.50175787,  0.61796511]]))

In [254]:
np.random.seed(42)
np.random.randint(3)


2

In [263]:
print(np.random.seed(434444444))
print(np.random.rand(3))
print(np.random.randn(3))
print(np.random.randint(1, 10, size=5))
print(np.random.choice([1,2,3], size=5))

None
[0.74634487 0.51539531 0.95406441]
[ 0.2495361   0.64564669 -0.31008112]
[6 6 3 3 8]
[2 2 3 2 1]


In [273]:
arr = np.array([1, np.nan, 3])


In [274]:
print(np.isnan(arr))


[False  True False]


In [275]:
arr


array([ 1., nan,  3.])

In [276]:
np.nan_to_num(arr)


array([1., 0., 3.])

# BAD
result = []
for i in range(len(a)):
    result.append(a[i] * 2)

# GOOD
a * 2

In [ ]:
arr = np.array([10, 20, 30, np.nan, 40])
mean=np.nanmean(arr)
print(mean)
filter=arr[arr>mean]
filter
normalize=(arr-np.nanmean(arr))/np.nanstd(arr)
print(normalize)




25.0
[-1.34164079 -0.4472136   0.4472136          nan  1.34164079]


In [291]:
mat = np.array([[1,2,3],
                [4,5,6]])
a,b,c=np.split(mat,3,axis=1)
np.max(a)

np.int64(4)

In [294]:
col_max = np.max(mat, axis=0)
print(col_max)

[4 5 6]


In [295]:
arr[np.isnan(arr)] = mean

In [296]:
salaries = np.array([50000, 60000, np.nan, 80000, 120000, np.nan])

In [299]:
mean=np.nanmean(salaries)
salaries=np.nan_to_num(salaries,nan=mean)
salaries

array([ 50000.,  60000.,  77500.,  80000., 120000.,  77500.])

In [309]:
norm_salaries=(salaries-np.mean(salaries))/np.std(salaries)

In [310]:
print(norm_salaries)

[-1.25628853 -0.79945634  0.          0.11420805  1.94153682  0.        ]


In [315]:
outliers=salaries[np.abs(norm_salaries)>2]
outliers


array([], dtype=float64)

In [317]:
summary = {
    "mean": np.mean(salaries),
    "median": np.median(salaries),
    "std": np.std(salaries),
    "max": np.max(salaries),
    "min": np.min(salaries)
}
summary

{'mean': np.float64(77500.0),
 'median': np.float64(77500.0),
 'std': np.float64(21889.875894272827),
 'max': np.float64(120000.0),
 'min': np.float64(50000.0)}

In [319]:
data = np.vstack((salaries, norm_salaries))
data

array([[ 5.00000000e+04,  6.00000000e+04,  7.75000000e+04,
         8.00000000e+04,  1.20000000e+05,  7.75000000e+04],
       [-1.25628853e+00, -7.99456337e-01,  0.00000000e+00,
         1.14208048e-01,  1.94153682e+00,  0.00000000e+00]])

In [321]:
cov_matrix = np.cov(data)
cov_matrix

array([[5.75000000e+08, 2.62678511e+04],
       [2.62678511e+04, 1.20000000e+00]])